add phases, sections and questions to template payload via jbuilder
CDLUC3/dmptool pull request #356
Opened 2022-06-15 20:26 UTC by miggall

Enhancements # .
Add optional url param for displaying phases -> sections -> questions in templates api endpoint

Changes proposed in this PR:
- if a v2 API user queries the template endpoint and passes the url parameter `show_phases=true`, the phase and its subsequent sections and questions will be included in the payload.

- updated the testing spec to include tests for phases (or lack thereof). 
- can run full test suite or test only this addition
- `bundle exec rspec spec/views/api/v2/templates/index.json.jbuilder_spec.rb` 

### Note
The code of conduct states I should branch off of `development` but that branch is a few months behind `main` so this PR is based off of `main`. I can base it off `development` and resubmit if needed

2022-06-17 17:02 UTC, briri requested changes
Thanks @miggall this looks good overall. 

I have updated the main branch to address the failures with the Brakeman tests and also updated the applications Gem and JS dependencies 

Can you please: 
- rebase your branch off of the main branch to pull in the latest fixes mentioned above
- run `bin/rubocop -a` which will auto-fix any code style issues
- fix the issues with the specs I commented on here
- add specs for the new sections and questions views

2022-06-17 17:02 UTC, briri commented on spec/views/api/v2/phases/_show.json.jbuilder_spec.rb
> +    scheme = create(:identifier_scheme, name: 'ror')
No need to create an identifier_scheme or identifier here. Phases don't use them,

2022-06-17 17:02 UTC, briri commented on spec/views/api/v2/phases/_show.json.jbuilder_spec.rb
> +    @org.reload
you have not defined `@org` so this fails. You can just delete the line, I don't see it used anywhere below

2022-06-17 17:02 UTC, briri commented on spec/views/api/v2/phases/_show.json.jbuilder_spec.rb
> +      expect(@template[:created]).to eql(@phase.created_at.to_formatted_s(:iso8601))
think these 2 should be `@json[:created]` and `@json[:modified]` instead of `@template`

2022-06-17 17:02 UTC, briri commented on spec/factories/phases.rb
> +      sections { 1 }
This is having unintended consequences on other tests and causing them to fail.

2022-06-17 17:02 UTC, briri commented on spec/factories/sections.rb
> +      questions { 1 }
This is having unintended consequences on other tests and causing them to fail.

2022-06-17 17:02 UTC, briri commented on spec/factories/templates.rb
> +      phases { 1 }
This is having unintended consequences on other tests and causing them to fail. Its better to just specify how many you want when constructing the record (e.g. `@template = template(:create, phases: 2)`

2022-06-17 17:02 UTC, briri commented on spec/views/api/v2/phases/_show.json.jbuilder_spec.rb
> +    @phase = create(:phase)
change this to `@phase = create(:phase, sections: 1)` after you remove your changes to the factories.

2022-06-17 17:02 UTC, briri commented on spec/views/api/v2/templates/index.json.jbuilder_spec.rb
> +      expect(@json[:items].first[:dmp_template][:phases].length).to eql(1)
this will fail once you remove your changes to the factories. To fix, just add `, phases: 1` to the call to create the first template at the top of this file

2022-06-17 20:17 UTC, miggall commented
Yikes! Thought I ran rubocop in the IDE before this PR to avoid those errors. Thanks for the quick review especially on the testing. I'll get these edits in and be a little more thorough.

With your edits I should expect Brakeman, Rubocop (after I fix), ESLint and the Accessibility checks to pass but MySQL and Postgres fail, correct?

2022-06-17 21:04 UTC, briri commented
Ha. no worries at all. I do it all the time, there are a ton of 'fixed Rubocop' or 'Make Rubocop happy' commits in this codebase. ;)

Once you've rebased from main, all tests should be passing. The changes in this PR to the spec/factories were causing some of the other tests to fail because they were checking the phase, section or question counts and the new default was putting them off by one. 

We do have a couple of tests that fail randomly on the Postgres and MySQL jobs due to either an unexpected string from the Faker gem we use to provide random-ish data which sometimes causes failures (e.g. expecting `'Jane Doe & Associates' == 'Jane Doe &amp; Associates'`). When those happen I usually just restart the job. We haven't had time to try and chase them down.

2022-06-21 23:33 UTC, miggall commented on spec/factories/templates.rb
> +      phases { 1 }
reverted and now using recommended `@template = template(:create, phases: 2`

2022-06-23 14:57 UTC, briri approved these changes
thanks for making these changes @miggal!

2022-06-23 15:28 UTC, briri commented
everything looks good. there are a few tests failing in Postgres. I'm going to look into these and see if I can fix

2022-06-23 15:36 UTC, merged